### ISSUE TITLE
Full screen video messes up layout on exit

### ISSUE THREAD

**Issue by Razorholt** [react-native-community/react-native-webview#1022]
When I play video in full screen with device on portrait position and exit, it's all fine. However, when I play video in full screen, turn the device to landscape and exit, the layout of the whole app gets completely messed up.

package.json

> {
>   "main": "node_modules/expo/AppEntry.js",
>   "scripts": {
>     "start": "expo start",
>     "android": "expo start --android",
>     "ios": "expo start --ios",
>     "web": "expo start --web",
>     "eject": "expo eject"
>   },
>   "dependencies": {
>     "@react-native-community/netinfo": "^4.6.0",
>     "expo": "^35.0.0",
>     "expo-av": "^7.0.1",
>     "expo-barcode-scanner": "~7.0.0",
>     "expo-constants": "~7.0.0",
>     "expo-device": "^1.0.0",
>     "expo-font": "~7.0.0",
>     "expo-image-picker": "~7.0.0",
>     "expo-intent-launcher": "~7.0.0",
>     "expo-localization": "^7.0.0",
>     "expo-permissions": "~7.0.0",
>     "expo-speech": "^7.0.0",
>     "expo-task-manager": "~7.0.0",
>     "expo-video-player": "^1.5.1",
>     "firebase": "^6.3.3",
>     "native-base": "^2.13.5",
>     "prop-types": "^15.7.2",
>     "react": "16.8.3",
>     "react-dom": "16.8.3",
>     "react-native": "0.59.10",
>     "react-native-animatable": "^1.3.3",
>     "react-native-animated-flatlist": "0.0.3",
>     "react-native-app-intro-slider": "^2.0.1",
>     "react-native-button": "^2.4.0",
>     "react-native-camera-kit": "^8.0.0",
>     "react-native-device-info": "^2.3.2",
>     "react-native-elements": "^1.1.0",
>     "react-native-gesture-handler": "~1.3.0",
>     "react-native-htmlview": "^0.15.0",
>     "react-native-image-gallery": "^2.1.5",
>     "react-native-modal": "^11.4.0",
>     "react-native-modal-datetime-picker": "^7.6.0",
>     "react-native-parallax-swiper": "^1.1.7",
>     "react-native-parsed-text": "0.0.21",
>     "react-native-picker-select": "^6.3.0",
>     "react-native-reanimated": "~1.2.0",
>     "react-native-render-html": "^4.1.2",
>     "react-native-scalable-image": "^1.0.0",
>     "react-native-scrollable-tab-view": "^0.10.0",
>     "react-native-simple-animations": "^0.2.1",
>     "react-native-tts": "^3.0.0",
>     "react-native-unimodules": "0.6.0",
>     "react-native-vector-icons": "^6.6.0",
>     "react-native-web": "^0.11.7",
>     "react-native-webbrowser-with-back": "^1.0.36",
>     "react-native-webview": "^7.5.1",
>     "react-navigation": "^4.0.6",
>     "react-navigation-drawer": "^2.0.0",
>     "react-navigation-stack": "^1.10.2",
>     "react-navigation-tabs": "^2.5.6",
>     "react-redux": "^7.1.0",
>     "redux": "^4.0.4",
>     "shorthash": "0.0.2"
>   },
>   "devDependencies": {
>     "babel-preset-expo": "^7.0.0"
>   },
>   "private": true
> }

app.json

> {
>   "expo": {
>     "privacy": "public",
>     "sdkVersion": "35.0.0",
>     "platforms": [
>       "ios",
>       "android",
>       "web"
>     ],
>     "version": "1.0.0",
>     "orientation": "portrait",
>     "icon": "./assets/icon.png",
>     "splash": {
>       "image": "./assets/splash.png",
>       "resizeMode": "cover",
>       "backgroundColor": "#156aa7"
>     },
>     "updates": {
>       "fallbackToCacheTimeout": 0
>     },
>     "assetBundlePatterns": [
>       "**/*"
>     ],
>     "ios": {
>       "supportsTablet": true,
>       "bundleIdentifier": "com.revert.project"
>     },
>     "description": "",
>     "androidStatusBar": {
>       "barStyle": "light-content",
>       "backgroundColor": "#000"
>     },
>     "androidNavigationBar": {
>       "visible": false,
>       "barStyle": "light-content",
>       "backgroundColor": "#000"
>     }
>   }
> }

**Comment by nicolaspavlotsky** [comment]
Have you found any solution?

**Comment by Razorholt** [comment]
This is what I posted on the Expo forum (edited):
---

The problem, as I understand it, is because you probably set the orientation to “portrait” in app.json. Therefore, no matter the position of the device, the screen will remain in portrait mode, as intended.

However, when you play a video through webview, iOS will not respect the default orientation in app.json and will update the screen orientation anyway. When played in portrait and exited in portrait position, that’s fine but if you turn your device in landscape and exit full screen then the orientation will be stuck in landscape, overwriting your default mode in app.json. 

The ideal solution would be to reset the orientation to portrait after you exit the fullscreen mode. I don't know how to do that, unfortunately.

Here is the closest solution I found:

```
import { ScreenOrientation } from "expo";

  componentDidMount() {
    ScreenOrientation.unlockAsync();
    ScreenOrientation.addOrientationChangeListener(async event => {
      if (event.orientationInfo.orientation === "LANDSCAPE") {
        //Alert.alert("landscape");
        await ScreenOrientation.lockAsync(
          ScreenOrientation.OrientationLock.PORTRAIT_UP
        );
      } else {
// Because sometimes it get stuck
        await ScreenOrientation.lockAsync(
          ScreenOrientation.OrientationLock.PORTRAIT_UP
        );
      }
    });
}
```
The first time you play the video in fullscreen and move from portrait position to landscape, it will go back to portrait mode. Try that move one more time and it should work.

I know it’s clumsy and hackish but that’s all I got so far… Unless you know how to make iOS communicate the actual screen orientation to react.

**Comment by nicolaspavlotsky** [comment]
Oh I thought you were having this problem on Android. On iOS works fine for me, but on Android if I hit the full screen button it goes to full screen but then when I hit it again it goes out of full screen but it looks messed up.

**Comment by Razorholt** [comment]
If it looks messed up it's probably an orientation issue. Check the status of the orientation after you exit the full screen mode.

**Comment by zchwyng** [comment]
I'm having the same problem.

**Comment by nicolaspavlotsky** [comment]
@zchwyng have you found a solution?

**Comment by zchwyng** [comment]
@nicolaspavlotsky Yes, I found a solution based on @Razorholt suggestion. I have not tested this on Android though... 

I was having 2 issues:
1. Enter fullscreen video -> Turn to landscape -> Exit video = Layout messed up (solved by @Razorholt) 
2.  Enter fullscreen video -> Turn to landscape -> Turn to portrait still in full screen -> Exit video = Layout messed up 

My solution was two methods for playing and pausing the video:

`handlePlayExternalVideo = () => {
    this.setState({ playingExternalVideo: true }, async () => {
      // NOTE: in order to solve a layout issue when exiting full screen landscape videos, we unlock ScreenOrientation in order to reset it later.
      await ScreenOrientation.unlockAsync()

      const listener = ScreenOrientation.addOrientationChangeListener(
        async orientation => {
          if (
            orientation.orientationInfo.orientation ===
            ScreenOrientation.Orientation.LANDSCAPE
          ) {
            // NOTE: in order to solve bug where layout was messed up if you went full screen landscape then full screen portrait before exiting, we lock to landscape once it is detected once
            await ScreenOrientation.lockAsync(
              ScreenOrientation.Orientation.LANDSCAPE
            )
            ScreenOrientation.removeOrientationChangeListener(listener)
          }
        }
      )
    })
  }`

and

`handlePauseExternalVideo = async () => {
    await ScreenOrientation.lockAsync(ScreenOrientation.Orientation.PORTRAIT_UP)
    this.setState({ playingExternalVideo: false })
  }`

**Comment by Razorholt** [comment]
I thought I'd share the solution I found. 

When you exit the video from full screen in LANDSCAPE although the app is locked in PORTRAIT, the phone will honor the orientation but will mess up with the layout of your app - It will not unlock the orientation. So suddenly, the width and height have switched although the app is still stuck in PORTRAIT.

Two main solutions to that issue:

1. After you're done with the video, unlock the orientation, change it to LANDSCAPE, then back to PORTRAIT. Not visually pleasing but it works.
2. Update the Dimensions (see bellow):

Using hooks & React-Navigation 5.0:

```
const [OrientationMode, setOrientationMode] = useState({
    width: Dimensions.get("window").width,
    height: Dimensions.get("window").height
  });

  const CheckMode = ({ setOrientationMode }) => {
    const Width = Dimensions.get("window").width;
    const Height = Dimensions.get("window").height;
    const DimWidth = Width > Height ? Height : Width;
    const DimWHeight = Width > Height ? Width : Height;
    setOrientationMode({ width: DimWidth, height: DimWHeight });
  };
```

Then I call the function anywhere I need to (onRefresh, Render, etc...):
`CheckMode({ setOrientationMode });`

When rendering, just use the following consts:

```
const width = OrientationMode.width;
const height = OrientationMode.height;
```

If you are still using Class, State etc... Then you may use this:
```
state = {
    width: Dimensions.get("window").width,
    height: Dimensions.get("window").height
}
```

Create a the function
```
_CheckMode = () => {
    const Width = Dimensions.get("window").width;
    const Height = Dimensions.get("window").height;
    const DimWidth = Width > Height ? Height : Width;
    const DimWHeight = Width > Height ? Width : Height;
    this.setState({
      width: DimWidth,
      height: DimWHeight,
    });
}
```

Use it
`this._CheckMode();`

While rendering
```
const width = this.state.width;
const height = this.state.height;
```

 React Native experts, feel free to contribute and pretty up my codes. No feelings with be hurt in the process :)

**Comment by safaiyeh** [comment]
Appreciate the example, once it is finalized maybe we should add this the docs?

**Comment by bkoether** [comment]
This is still an issue.

@Razorholt I get the basic idea of the solution you posted. But can you go more into details how/where you use the `width` and `height` variables? For me, it is the navigation (header and tab bar) that are messed up after playing the full screen video. So I'm not sure how this approach would solve the problem. Would appreciate your feedback.

**Comment by Razorholt** [comment]
@bkoether At first I thought, just like you, that the problem was related to the header only. But it's not.  It is an React-Native orientation status issue.
Now, to be clear, my "solution" works well when your orientation is locked.
Do you allow both Landscape and Portrait modes?

**Comment by bkoether** [comment]
@Razorholt Thanks for replying! The orientation is locked to portrait. The project I'm working on uses class components.

So I guess my questions would be
1: When would you call `this._CheckMode();` Is there a listener as to when a fullscreen video is closed?
2: How do you use the variables in this snippet?
```
const width = this.state.width;
const height = this.state.height;
```
Or is it just enough to have those set in the `render()` method?

**Comment by Razorholt** [comment]
No problem! Put the `this._CheckMode();` under ComponentDidMount - You can use the` willfocus` listener also.

**Comment by Razorholt** [comment]
TBH, I moved away Classes over a year ago so I have to remember how I was handling the issue back then.. :)
I know that I had something like that:

```
import { ScreenOrientation } from "expo";

 constructor(props) {
    super(props);
    this.state = {
      width: Dimensions.get("window").width,
      height: Dimensions.get("window").height
    };
  }

_CheckMode = () => {
    const Width = Dimensions.get("window").width;
    const Height = Dimensions.get("window").height;
    const DimWidth = Width > Height ? Height : Width;
    const DimWHeight = Width > Height ? Width : Height;
    this.setState({
      width: DimWidth,
      height: DimWHeight,
    });
}

 componentDidMount() {
    ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.PORTRAIT_UP);
    const { navigation } = this.props;
    this.focusListener = navigation.addListener("willFocus", () => {
        this._CheckMode();
    });
  }
  componentWillUnmount() {
    this.focusListener.remove();
  }
```

Also, after you exit fullscreen in landscape mode, is the whole layout messed up or just the RN header?

**Comment by bkoether** [comment]
RN header and Tab nav is messed up.

**Comment by Razorholt** [comment]
The default height of the RN header is different depending on the Orientation - smaller in Landscape - so give a height to the RN Header, it will overwrite the default one. Apply the same logic to the Tabs. 

Example:
 ```
static navigationOptions = () => {
    return {
      headerLeft: BackButton,
      headerTitle: <Text style={styles.titleTop}>Settings</Text>,
      headerStyle: {
        backgroundColor: "#145b8f",
        height: 50
      },
      headerTintColor: "#fff",
      headerTitleStyle: {
        fontWeight: "normal"
      }
    };
  };
```

**Comment by summerkiflain** [comment]
For me this is still not resolved, all the above solutions depend on the navigation throwing some event and listeners unlock & lock direction of the app again, in my case webview is on the same page as main class, so coming out of the landscape mode doesn't generate any event for navigation and so no unlocking / locking direction again. even if it does that is not a proper solution, proper solution would be that webview throw an event back to react component or react-navigation detecting the actual app direction and applying the direction mentioned in 'app.json' for the app again after exiting webview in the landscape mode.

**Comment by Viacheslav80** [comment]
Hi! For me worked that. remove "orientation": "portrait" from app.json, then add the following to the ios node:
 "infoPlist": { "UISupportedInterfaceOrientations~iphone": [ "UIInterfaceOrientationPortrait" ]}

**Comment by t0ma5h** [comment]
This is still an issue. Especially  when using flatling. Here's a snack to reproduce this: 
https://snack.expo.dev/_niEY54oN

Steps to reproduce: 
1. Scroll to the bottom of the list 
2. Play the last item
3. Enter full screen 
4. Rotate the device 
5. Go back 

After doing this a couple of times, the webview will just disappear.

**Comment by t0ma5h** [comment]
Still an issue
