### ISSUE TITLE
Tried to register two views with the same name RNCWebView

### ISSUE THREAD

**Issue by legion-zver** [react-native-community/react-native-webview#373]
- react-native-webview 5.2.4
- RN 0.58.6

On the 5.2.1 version everything works well

**Comment by Titozzz** [comment]
I think it's just a cache issue, clean / rebuild maybe?

**Comment by webexpert4rv** [comment]
I am still getting this error after upgrade  project  from 0.55.3 to 0.59.8 react native version

**Comment by jamonholmgren** [comment]
I would recommend cleaning all caches and rebuilding.

**Comment by mikaoelitiana** [comment]
Cleaning and rebuilding doesn't fix this issue for me

**Comment by waheedakhter** [comment]
Facing the same issue. cleaning and rebuilding not working for me either.

**Comment by waheedakhter** [comment]
Found the solution. The reason I was facing this issue was that I had copied and pasted some folders from node_modules as a backup somewhere in project. as soon as I deleted that folder. the error went away.

**Comment by khalidos32** [comment]
i have the same issue i'm trying to use a package that's using react-native -webview. any solution

**Comment by massivebrains** [comment]
Incase anyone is still facing this issue, here is what i did that fixed mine.

 i Ran `npm ls react-native-webview`

Then i figured the package that has installed another version of react-native-webview, which in my case was @shoutem/ui@1.0.1

So i removed my react-native-webview and reinstalled with the exact same version of the one in @shoutem/ui@1.0.1

**Comment by massivebrains** [comment]
@khalidos32  Try that and let me know if it works.

**Comment by pragneshpj** [comment]
anyone have proper solution.

**Comment by mikaoelitiana** [comment]
I solved it by using same `react-native-webview` version as the one required by `react-native-android-fullscreen-webview-video`. 
You may have one library depending on a different `react-native-webview` and can check the version using `yarn why react-native-webview`

**Comment by nihp** [comment]
I am also facing the same issue. I have removed node_modules and reinstalled again. But still the issue exist.

Any solution for this.

**Comment by developerashish01** [comment]
any solution?

**Comment by pragneshpj** [comment]
can you please check your external packages use the **react-native-webview** in dependencies.
if you then you have to remove one and keep only one **react-native-webview** in your project.

i've tried with this it worked.

**Comment by sregg** [comment]
if you have a package that has `react-native-webview` as a dep (in my case `react-native-linkedin`), should I install `react-native-webview` with the same version as the one in my dep or should I remove from my own `package.json`?

**Comment by KristineTrona** [comment]
I am having the same issue. In my case I was using the lastest version 7.4.3 of ``react-native-webview`` and ``react-native-render-html``, which at this point requires ``react-native-webview 5.12.0``. Installing react-native-webview 5.12.0 version instead fixed the issue with trying to register two views with the same name. However, when submitting my app for appStore on ios I received an error, that using UIWebView was deprecated. This issue was only fixed in react-native-webview 7.0.1 and on, so I am in a bit of a pickle here, as downgrading to use the same react-native-webview version is not always a viable option.

**Comment by ahartzog** [comment]
@KristineTrona - you're welcome to use my fork if you like. 

https://github.com/nerdfitness/react-native-render-html/tree/move-webview-peer-dep

I've just moved react-native-webview to a peer dependancy inside react-native-render-html

The only other change from the base version is to add a prop to supposed self-closing tags in RNRH. 

You could also just fork your own version and change it to a peer dependancy.

**Comment by tmtung144** [comment]
![Screen Shot 2019-11-22 at 01 06 13](https://user-images.githubusercontent.com/19670776/69364131-55c02300-0cc4-11ea-9693-2a0249d2777c.png)
Tried the fork of @ahartzog but it still failed

**Comment by zeeshanjan82** [comment]
any fix for this issue?

**Comment by ashu090990** [comment]
![webview](https://user-images.githubusercontent.com/13793718/70026466-e4d31200-15c5-11ea-870a-73add8f02025.jpg)

**Comment by tmtung144** [comment]
I use **react-native-render-html**, and it hasn't updated to the new version in which it requires obsolete old WebView, if you use this library just like me, use [pull-request](https://github.com/archriss/react-native-render-html/pulls) accordingly suits you

**Comment by yodaheis** [comment]
> any fix for this issue?

you must have two different versions of the same package installed. do 'yarn why react-native-webview' and update your version to use the same as the dependency of the package

**Comment by luatnd** [comment]
> Found the solution. The reason I was facing this issue was that I had copied and pasted some folders from node_modules as a backup somewhere in project. as soon as I deleted that folder. the error went away.

Exactly my issue! Remove the source folder then problem solved!
my package.json
```
"react-native-webview": "file:node_modules_dev/react-native-webview",
```
So after I `yarn`
My project have 2 folder:
* node_modules_dev/react-native-webview
* node_modules/react-native-webview

That cause problem.
But I don't know why, my project has so many local development node_modules, the issue come with react-native-webview only.

**Comment by emrexhepi** [comment]
Guys if you still have this problem here is the solution:
1. Check which version of web-view is installed from packages 'npm ls react-native-webview'
2. Install the same version as your package
3. Run 'npm ddp' so it will defer the duplicates.

Cheers,

**Comment by hardikshah197** [comment]
Deleting and reinstalling node_module also does work out, the issue still remains the same

**Comment by ramzihere** [comment]
any solution for this i have a package that has react-native-webview as a dep (in my case react-native-linkedin) i tried to match versions of both but issue still same

**Comment by hardikshah197** [comment]
Check your version by running `npm ls react-native-webview` and you can see the **version difference** there if you are having this issue,
Now delete that recently installed that package and reinstall it with the required version
If you are having the same issue in **"react-native-linked"**, do a similar thing with that also.

**Comment by hardikshah197** [comment]
> any solution for this i have a package that has react-native-webview as a dep (in my case react-native-linkedin) i tried to match versions of both but issue still same
Solution:-
Check your version by running npm ls react-native-webview and you can see the version difference there if you are having this issue,
Now delete that recently installed that package and reinstall it with the required version
If you are having the same issue in "react-native-linked", do a similar thing with that also.

**Comment by hardikshah197** [comment]
For **non-Expo applications**, the above-given solution does work out.
So, for ***react-native applications*** made in **ANDROID Studio** here is the solution:-

 - Replace your **react-native-linked** dependency version with its
   the latest version currently latest is **2.1.1** which gives this error,
   replace it with this link - [version][1]
   "https://github.com/xcarpentier/react-native-linkedin.git" along with
   required changes.
 - Delete and reinstall node_module.
 - After installing, either delete the **WEBVIEW** folder from
   "react-native-linked" in node_module manually or write the below the
   line in your script in the package.json file:
`"postinstall": "npx jetifier; patch-package; rm -rf ./node_modules/react-native-linkedin/node_modules/react-native-webview",
` after "start" key.

  [1]: https://github.com/xcarpentier/react-native-linkedin.git

**Comment by roycechua23** [comment]
This problem could also be called by inconsistent react-native-web versions in your **package.json** and **package-lock.json**. Try to search for _**react-native-webview**_ in your editor like VS Code then try to compare if there are inconsistent versions from the version you knew you installed. 

In my case 8.0.4 was the last version but when I installed the latest 11.2.1 I found that the lock files weren't updated like I expected it to. After changing it manually, the problem was solved.

**Comment by eramudeep** [comment]
still facing the same issue, tried everything so far. 
now f*cked Up :(

**Comment by himanshuprimotech** [comment]
I am get this error while running my project could anyone please let me know the solution? I have cleared the cache and Reinstalled the node_modules as well.

![Screenshot_20221229_152842](https://user-images.githubusercontent.com/118181609/209940914-b0bd4761-1fbc-4b46-bc89-4d7b127f80a8.png)

**Comment by eramudeep** [comment]
> I am getting this error while running my project could anyone please let me know the solution? I have cleared the cache and Reinstalled the node_modules as well.
> 
> ![Screenshot_20221229_152842](https://user-images.githubusercontent.com/118181609/209940914-b0bd4761-1fbc-4b46-bc89-4d7b127f80a8.png)

this will help
https://github.com/react-native-webview/react-native-webview/issues/373#issuecomment-525311048

**Comment by himanshuprimotech** [comment]
> > I am getting this error while running my project could anyone please let me know the solution? I have cleared the cache and Reinstalled the node_modules as well.
> > ![Screenshot_20221229_152842](https://user-images.githubusercontent.com/118181609/209940914-b0bd4761-1fbc-4b46-bc89-4d7b127f80a8.png)
> 
> this will help [#373 (comment)](https://github.com/react-native-webview/react-native-webview/issues/373#issuecomment-525311048)



Thanks for answering the question. 
Now the Point is How I have to remove the react-native-webview
![f_PNIc92hKTe4z58SslXqkoHyDAbvJZtEM](https://user-images.githubusercontent.com/118181609/209948662-6917882f-6102-4af9-b95e-324dce3fe7b0.png)

**Comment by eramudeep** [comment]
i used this solution couple of times 
https://stackoverflow.com/a/65341806/9302583
this happens when you have installed multiple versions of Webview.

**Comment by marlti7** [comment]
conflict with other package , see it`s package.json if has peerDependencies with react-native-webview,  annotation or delete it, restart will work

**Comment by solominh** [comment]
In my case, i just close the yarn start process. Then i start with clear cache: yarn start -c. Problem sovled

**Comment by Oludefiyinfoluwa06** [comment]
If you have your quill editor within a scroll view, I think it also causes the issue. That was my own case
