### ISSUE TITLE
 error: method getJSEventName in enum ScrollEventType cannot be applied to given types;

### ISSUE THREAD

**Issue by nicolasdet** [react-native-community/react-native-webview#579]
**Bug description:**

In my package.json i have a dependency : 
"react-native-webview": "^5.3.0". 

Since "version": "5.8.1" all was OK and i got no problem with this package. 
Now we are in "version": "5.9.0" and i got a breaking Bug. 

**To Reproduce:**

- npm install  
- react-native link 
 - react-native run-android

**Error message:**

RNCWebViewManager.java:452: error: method getJSEventName in enum ScrollEventType cannot be applied to given types;

**Screenshots/Videos:**
![bugModuleRn](https://user-images.githubusercontent.com/13063865/57941331-ee698680-78ce-11e9-929e-b95eebe9b439.png)

**Environment:**
 - OS: Windows 10 pro
 - react-native version: 0.59.0
 - react-native-webview version: 5.9.0

**Comment by Josephdias92** [comment]
This is already been resolved in https://github.com/react-native-community/react-native-webview/releases/tag/v6.0.1

**Comment by Josephdias92** [comment]
Is there a way you'll can create a patch with 5.9.1 cos I don't want breaking changes.

**Comment by nicolasdet** [comment]
Thanks. I should have paid attention to the most recent release. My npm took 5.9.0 when npm install. Sorry.

**Comment by nicolasdet** [comment]
i'm not

**Comment by nicolasdet** [comment]
I am not really a java developer and do not know how this package is made. But If I have time this weekend, I will look into it.
Thank you for the help, i should have been more careful and pay more attention to the latest version..

**Comment by Josephdias92** [comment]
Thanks. I was waiting for the full screen PR to be merged for more then two months. ☹️

**Comment by Titozzz** [comment]
Hello I fixed 6.0.2 and also released 5.9.1 if you don't want to upgrade!

**Comment by briankoey** [comment]
v5.9.1 still experienced the same issue.

**Comment by HyperNovax** [comment]
Same issue with the version 6.X.X. It's working good with 5.8.2. 
My project use react native 0.57.2.

**Comment by davidnuvolar** [comment]
@Titozzz in my case I tried with 5.10.0 and the issue is still there. Impossible to have this running on Android.

**Comment by HyperNovax** [comment]
It's fixed for me, I upgraded react native in lastest version (0.59.8).
